import { createServerClient } from '@supabase/ssr'
import type { Database } from '@/types/database'
import { resend } from './resend'

export interface BulkUploadRisk {
  riskScore: number
  riskLevel: 'low' | 'medium' | 'high' | 'critical'
  riskFlags: string[]
  shouldBlock: boolean
  shouldFlag: boolean
  shouldRequireReview: boolean
  warningMessage?: string
}

export interface AbuseFlag {
  userId: string
  flagType: string
  flagReason: string
  severity: 'low' | 'medium' | 'high' | 'critical'
  evidence: Record<string, any>
  autoGenerated: boolean
}

class AbuseDetector {
  private supabase: any

  constructor(supabaseUrl: string, supabaseKey: string) {
    this.supabase = createServerClient<Database>(supabaseUrl, supabaseKey, {
      cookies: {
        getAll() { return [] },
        setAll() {},
      },
    })
  }

  /**
   * Analyze bulk upload for spam/abuse patterns
   */
  async analyzeBulkUpload(params: {
    userId: string
    uploadSize: number
    phoneNumbers: string[]
    duplicateRate: number
    highRiskNumbers: number
    ipAddress?: string
    userAgent?: string
  }): Promise<BulkUploadRisk> {
    const riskFlags: string[] = []
    let riskScore = 0

    // Check if user has active restrictions
    const { data: restrictions } = await this.supabase
      .from('account_restrictions')
      .select('restriction_type, reason')
      .eq('user_id', params.userId)
      .eq('is_active', true)
      .or('expires_at.is.null,expires_at.gt.' + new Date().toISOString())

    if (restrictions && restrictions.length > 0) {
      riskScore = 100
      riskFlags.push('account_has_active_restrictions')

      return {
        riskScore: 100,
        riskLevel: 'critical',
        riskFlags,
        shouldBlock: true,
        shouldFlag: true,
        shouldRequireReview: true,
        warningMessage: 'Upload blocked - account has active restrictions'
      }
    }

    // Analyze upload size patterns
    const sizeRisk = this.analyzeSizeRisk(params.uploadSize)
    riskScore += sizeRisk.score
    riskFlags.push(...sizeRisk.flags)

    // Analyze phone number patterns
    const phoneRisk = await this.analyzePhonePatterns(params.phoneNumbers, params.userId)
    riskScore += phoneRisk.score
    riskFlags.push(...phoneRisk.flags)

    // Analyze user history
    const historyRisk = await this.analyzeUserHistory(params.userId, params.uploadSize)
    riskScore += historyRisk.score
    riskFlags.push(...historyRisk.flags)

    // Analyze duplicate patterns
    const duplicateRisk = this.analyzeDuplicatePatterns(params.duplicateRate, params.uploadSize)
    riskScore += duplicateRisk.score
    riskFlags.push(...duplicateRisk.flags)

    // Determine risk level and actions
    riskScore = Math.min(riskScore, 100)
    const riskLevel = this.determineRiskLevel(riskScore)

    const result: BulkUploadRisk = {
      riskScore,
      riskLevel,
      riskFlags,
      shouldBlock: riskScore >= 80,
      shouldFlag: riskScore >= 60,
      shouldRequireReview: riskScore >= 40
    }

    if (result.shouldBlock) {
      result.warningMessage = 'Upload blocked due to high abuse risk'
    } else if (result.shouldFlag) {
      result.warningMessage = 'Upload flagged for review'
    }

    // Log the upload attempt
    await this.logBulkUpload({
      userId: params.userId,
      uploadSize: params.uploadSize,
      duplicateRate: params.duplicateRate,
      highRiskNumbers: params.highRiskNumbers,
      riskScore,
      riskFlags,
      ipAddress: params.ipAddress,
      userAgent: params.userAgent,
      status: result.shouldBlock ? 'blocked' : (result.shouldFlag ? 'flagged' : 'completed')
    })

    return result
  }

  private analyzeSizeRisk(uploadSize: number): { score: number; flags: string[] } {
    const flags: string[] = []
    let score = 0

    if (uploadSize > 1000) {
      score += 40
      flags.push('extremely_large_upload')
    } else if (uploadSize > 500) {
      score += 30
      flags.push('very_large_upload')
    } else if (uploadSize > 200) {
      score += 20
      flags.push('large_upload')
    } else if (uploadSize > 100) {
      score += 10
      flags.push('medium_upload')
    }

    return { score, flags }
  }

  private async analyzePhonePatterns(phoneNumbers: string[], userId: string): Promise<{ score: number; flags: string[] }> {
    const flags: string[] = []
    let score = 0

    // Check for sequential number patterns (sign of fake data)
    const sortedNumbers = phoneNumbers.map(num => num.replace(/\D/g, '')).sort()
    let sequentialCount = 0

    for (let i = 1; i < sortedNumbers.length; i++) {
      const current = parseInt(sortedNumbers[i].slice(-4))
      const previous = parseInt(sortedNumbers[i-1].slice(-4))
      if (current === previous + 1) {
        sequentialCount++
      }
    }

    if (sequentialCount > phoneNumbers.length * 0.3) {
      score += 50
      flags.push('sequential_phone_patterns')
    } else if (sequentialCount > phoneNumbers.length * 0.1) {
      score += 25
      flags.push('some_sequential_patterns')
    }

    // Check for repeated area codes/prefixes (could be legitimate for local business)
    const areaCodes = phoneNumbers.map(num => {
      const digits = num.replace(/\D/g, '')
      if (digits.startsWith('447') || digits.startsWith('44')) {
        return digits.substring(2, 5) // First 3 digits after +44
      } else if (digits.startsWith('07')) {
        return digits.substring(0, 3) // 070, 071, etc.
      }
      return null
    }).filter(Boolean)

    const uniqueAreaCodes = new Set(areaCodes).size
    const areaCodeRatio = uniqueAreaCodes / areaCodes.length

    if (areaCodeRatio < 0.1 && phoneNumbers.length > 50) {
      score += 15
      flags.push('very_limited_area_codes')
    } else if (areaCodeRatio < 0.3 && phoneNumbers.length > 100) {
      score += 10
      flags.push('limited_area_codes')
    }

    return { score, flags }
  }

  private async analyzeUserHistory(userId: string, currentUploadSize: number): Promise<{ score: number; flags: string[] }> {
    const flags: string[] = []
    let score = 0

    // Get user account age
    const { data: profile } = await this.supabase
      .from('profiles')
      .select('created_at, business_name')
      .eq('id', userId)
      .single()

    if (profile) {
      const accountAge = (Date.now() - new Date(profile.created_at).getTime()) / (1000 * 60 * 60 * 24)

      // New account with large upload
      if (accountAge < 1 && currentUploadSize > 100) {
        score += 40
        flags.push('new_account_large_upload')
      } else if (accountAge < 7 && currentUploadSize > 200) {
        score += 30
        flags.push('very_new_account_large_upload')
      }
    }

    // Check recent upload frequency
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
    const { data: recentUploads } = await this.supabase
      .from('bulk_upload_log')
      .select('upload_size, created_at')
      .eq('user_id', userId)
      .gte('created_at', sevenDaysAgo.toISOString())

    if (recentUploads) {
      const uploadCount = recentUploads.length
      const totalSize = recentUploads.reduce((sum: number, upload: any) => sum + upload.upload_size, 0)

      if (uploadCount > 10) {
        score += 35
        flags.push('excessive_upload_frequency')
      } else if (uploadCount > 5) {
        score += 20
        flags.push('high_upload_frequency')
      }

      if (totalSize > 2000) {
        score += 25
        flags.push('massive_weekly_volume')
      } else if (totalSize > 1000) {
        score += 15
        flags.push('high_weekly_volume')
      }
    }

    // Check for previous flags
    const { data: previousFlags } = await this.supabase
      .from('account_flags')
      .select('flag_type, severity')
      .eq('user_id', userId)
      .is('resolved_at', null)

    if (previousFlags && previousFlags.length > 0) {
      const criticalFlags = previousFlags.filter((flag: any) => flag.severity === 'critical').length
      const highFlags = previousFlags.filter((flag: any) => flag.severity === 'high').length

      score += criticalFlags * 25 + highFlags * 15
      flags.push('has_unresolved_flags')
    }

    return { score, flags }
  }

  private analyzeDuplicatePatterns(duplicateRate: number, uploadSize: number): { score: number; flags: string[] } {
    const flags: string[] = []
    let score = 0

    // Very low duplicate rate for large uploads is suspicious (suggests non-customer data)
    if (uploadSize > 100 && duplicateRate < 2) {
      score += 30
      flags.push('suspiciously_low_duplicates')
    } else if (uploadSize > 50 && duplicateRate < 1) {
      score += 20
      flags.push('very_low_duplicates')
    }

    // Extremely high duplicate rate also suspicious
    if (duplicateRate > 80) {
      score += 25
      flags.push('extremely_high_duplicates')
    } else if (duplicateRate > 60) {
      score += 15
      flags.push('high_duplicates')
    }

    return { score, flags }
  }

  private determineRiskLevel(riskScore: number): 'low' | 'medium' | 'high' | 'critical' {
    if (riskScore >= 80) return 'critical'
    if (riskScore >= 60) return 'high'
    if (riskScore >= 40) return 'medium'
    return 'low'
  }

  /**
   * Create an abuse flag for an account
   */
  async flagAccount(flag: AbuseFlag): Promise<void> {
    try {
      const { error } = await this.supabase
        .from('account_flags')
        .insert({
          user_id: flag.userId,
          flag_type: flag.flagType,
          flag_reason: flag.flagReason,
          severity: flag.severity,
          evidence: flag.evidence,
          auto_generated: flag.autoGenerated
        })

      if (error) {
        console.error('Error creating account flag:', error)
        return
      }

      // Send alert for high severity flags
      if (flag.severity === 'high' || flag.severity === 'critical') {
        await this.sendAbuseAlert(flag)
      }

    } catch (error) {
      console.error('Failed to flag account:', error)
    }
  }

  /**
   * Log bulk upload attempt
   */
  private async logBulkUpload(params: {
    userId: string
    uploadSize: number
    duplicateRate: number
    highRiskNumbers: number
    riskScore: number
    riskFlags: string[]
    ipAddress?: string
    userAgent?: string
    status: string
  }): Promise<void> {
    try {
      await this.supabase
        .from('bulk_upload_log')
        .insert({
          user_id: params.userId,
          upload_size: params.uploadSize,
          duplicate_rate: params.duplicateRate,
          high_risk_numbers: params.highRiskNumbers,
          risk_score: params.riskScore,
          risk_flags: params.riskFlags,
          ip_address: params.ipAddress,
          user_agent: params.userAgent?.substring(0, 500),
          status: params.status
        })
    } catch (error) {
      console.error('Failed to log bulk upload:', error)
    }
  }

  /**
   * Send abuse alert to admin
   */
  private async sendAbuseAlert(flag: AbuseFlag): Promise<void> {
    if (!resend) {
      console.warn('Resend not configured - cannot send abuse alert')
      return
    }

    try {
      const { data: profile } = await this.supabase
        .from('profiles')
        .select('business_name, email')
        .eq('id', flag.userId)
        .single()

      const businessName = profile?.business_name || 'Unknown Business'
      const userEmail = profile?.email || 'Unknown Email'

      await resend.emails.send({
        from: 'Grow Our Reviews Security <security@growourreviews.com>',
        to: ['ed@growourreviews.com'],
        subject: `🚨 ${flag.severity.toUpperCase()} Abuse Alert - ${flag.flagType}`,
        html: `
          <h1>🚨 Abuse Detection Alert</h1>

          <div style="background: ${flag.severity === 'critical' ? '#fef2f2' : '#fff7ed'}; border-left: 4px solid ${flag.severity === 'critical' ? '#dc2626' : '#f59e0b'}; padding: 16px; margin: 20px 0;">
            <h2 style="color: ${flag.severity === 'critical' ? '#dc2626' : '#f59e0b'}; margin: 0 0 10px 0;">
              ${flag.severity === 'critical' ? 'CRITICAL' : 'HIGH'} SEVERITY ALERT
            </h2>
            <p><strong>Flag Type:</strong> ${flag.flagType}</p>
            <p><strong>User:</strong> ${businessName} (${userEmail})</p>
            <p><strong>Reason:</strong> ${flag.flagReason}</p>
            <p><strong>Auto-generated:</strong> ${flag.autoGenerated ? 'Yes' : 'No'}</p>
          </div>

          <h3>Evidence:</h3>
          <pre style="background: #f3f4f6; padding: 12px; border-radius: 6px; overflow-x: auto;">
${JSON.stringify(flag.evidence, null, 2)}
          </pre>

          <h3>Recommended Actions:</h3>
          <ul>
            <li><strong>Review account activity</strong> - Check recent uploads and SMS usage</li>
            <li><strong>Verify business legitimacy</strong> - Contact user if needed</li>
            <li><strong>Consider restrictions</strong> - Suspend uploads or SMS if confirmed abuse</li>
            <li><strong>Check for spam reports</strong> - Monitor customer feedback for complaints</li>
          </ul>

          <p><a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://app.growourreviews.com'}/admin/abuse-monitoring" style="background: #dc2626; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Review Account →</a></p>

          <p><strong>This is an automated security alert from your abuse detection system.</strong></p>
        `
      })
    } catch (error) {
      console.error('Error sending abuse alert:', error)
    }
  }
}

// Factory function
export function createAbuseDetector(supabaseUrl: string, supabaseKey: string): AbuseDetector {
  return new AbuseDetector(supabaseUrl, supabaseKey)
}