import { createServerSupabase } from '@/lib/auth'
import { NextRequest, NextResponse } from 'next/server'
import { getCurrentBillingPeriod, getNextBillingDate } from '@/lib/billing-cycle'
import { countNudgesSentInPeriod } from '@/lib/credit-usage'
import { generateToken } from '@/lib/generate-token'
import { createAbuseDetector } from '@/lib/abuse-detector'
import { DEFAULT_TRIAL_LIMIT } from '@/lib/pricing'
import type { Database } from '@/types/database'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createServerSupabase()

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser()
    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { customers, pendingCustomers = [], savePendingCustomers = false } = await request.json()

    if (!customers || !Array.isArray(customers) || customers.length === 0) {
      return NextResponse.json(
        { error: 'No customers provided' },
        { status: 400 }
      )
    }

    // SECURITY: Abuse detection for bulk uploads
    const abuseDetector = createAbuseDetector(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )

    // Extract phone numbers for analysis
    const phoneNumbers = customers.map((customer: any) => customer.normalizedPhone)
    const duplicateRate = pendingCustomers.length > 0
      ? ((customers.length - phoneNumbers.length) / customers.length) * 100
      : 0

    // Get request IP and user agent for logging
    const ipAddress = request.headers.get('x-forwarded-for') || 'unknown'
    const userAgent = request.headers.get('user-agent') || 'unknown'

    // Analyze upload for abuse patterns
    const riskAnalysis = await abuseDetector.analyzeBulkUpload({
      userId: user.id,
      uploadSize: customers.length,
      phoneNumbers,
      duplicateRate,
      highRiskNumbers: 0, // Will be calculated by duplicate check
      ipAddress,
      userAgent
    })

    // Block upload if high risk
    if (riskAnalysis.shouldBlock) {
      // Create flag for critical risk uploads
      if (riskAnalysis.riskLevel === 'critical') {
        await abuseDetector.flagAccount({
          userId: user.id,
          flagType: 'bulk_upload_blocked',
          flagReason: `Bulk upload blocked due to abuse risk: ${riskAnalysis.riskFlags.join(', ')}`,
          severity: 'high',
          evidence: {
            uploadSize: customers.length,
            riskScore: riskAnalysis.riskScore,
            riskFlags: riskAnalysis.riskFlags,
            ipAddress,
            userAgent: userAgent.substring(0, 200)
          },
          autoGenerated: true
        })
      }

      return NextResponse.json(
        {
          error: 'Upload blocked for security reasons. Please contact support if you believe this is an error.',
          riskScore: riskAnalysis.riskScore,
          riskFlags: riskAnalysis.riskFlags
        },
        { status: 403 }
      )
    }

    // Flag account for manual review if needed
    if (riskAnalysis.shouldFlag) {
      await abuseDetector.flagAccount({
        userId: user.id,
        flagType: 'bulk_upload_flagged',
        flagReason: `Bulk upload flagged for review: ${riskAnalysis.riskFlags.join(', ')}`,
        severity: riskAnalysis.riskLevel === 'high' ? 'high' : 'medium',
        evidence: {
          uploadSize: customers.length,
          riskScore: riskAnalysis.riskScore,
          riskFlags: riskAnalysis.riskFlags,
          ipAddress,
          userAgent: userAgent.substring(0, 200)
        },
        autoGenerated: true
      })
    }

    // Get user's profile and current usage
    const { data: profile } = await supabase
      .from('profiles')
      .select('monthly_request_limit, billing_cycle_date')
      .eq('id', user.id)
      .single()

    if (!profile) {
      return NextResponse.json(
        { error: 'Profile not found' },
        { status: 404 }
      )
    }

    // Check current billing period usage using personalized billing cycle
    let billingStart: Date
    let billingEnd: Date

    if ((profile as any).billing_cycle_date) {
      const billingPeriod = getCurrentBillingPeriod((profile as any).billing_cycle_date)
      billingStart = billingPeriod.start
      billingEnd = billingPeriod.end
    } else {
      // Fallback to calendar month if billing_cycle_date is not set
      const now = new Date()
      billingStart = new Date(now.getFullYear(), now.getMonth(), 1)
      billingEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59)
    }

    // Credits used this period = originals sent + nudges sent.
    const [{ data: originalsThisMonth }, nudgesThisMonth] = await Promise.all([
      supabase
        .from('review_requests')
        .select('id', { count: 'exact' })
        .eq('user_id', user.id)
        .gte('sent_at', billingStart.toISOString())
        .lte('sent_at', billingEnd.toISOString())
        .not('sent_at', 'is', null),
      countNudgesSentInPeriod(supabase, user.id, billingStart, billingEnd),
    ])

    const requestsSent = (originalsThisMonth?.length || 0) + nudgesThisMonth
    const monthlyLimit = (profile as any)?.monthly_request_limit || DEFAULT_TRIAL_LIMIT
    const requestsRemaining = Math.max(0, monthlyLimit - requestsSent)

    // Calculate next reset date for error messaging
    const nextResetDate = (profile as any).billing_cycle_date
      ? getNextBillingDate((profile as any).billing_cycle_date)
      : new Date(billingStart.getFullYear(), billingStart.getMonth() + 1, 1)

    // Process customers based on selection and remaining requests
    const customersToProcess = customers.slice(0, requestsRemaining)

    // Handle pending customers for future processing
    let pendingSavedCount = 0
    if (savePendingCustomers && pendingCustomers.length > 0) {
      try {
        // Save pending customers for next month's allocation
        const pendingInserts = pendingCustomers.map((customer: any) => ({
          user_id: user.id,
          name: customer.name,
          phone: customer.normalizedPhone,
          status: 'pending',
          created_at: new Date().toISOString()
        }))

        const { data: pendingData, error: pendingError } = await (supabase as any)
          .from('pending_customers')
          .insert(pendingInserts)
          .select('id')

        if (!pendingError && pendingData) {
          pendingSavedCount = pendingData.length
        }
      } catch (pendingErr) {
        console.error('Failed to save pending customers:', pendingErr)
        // Don't fail the whole upload if pending save fails
      }
    }

    if (customersToProcess.length === 0) {
      // Send plan limit reached email if user has hit their monthly limit
      if (requestsSent >= monthlyLimit) {
        try {
          await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/emails/plan-limit-reached`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              email: user.email,
              businessName: (profile as any)?.business_name || 'there',
              currentLimit: monthlyLimit,
              requestsUsed: requestsSent
            }),
          })
        } catch (error) {
          console.error('Failed to send plan limit email:', error)
        }
      }

      return NextResponse.json(
        { error: `No requests remaining in your plan. Your credits reset on ${nextResetDate.toLocaleDateString('en-GB')}.` },
        { status: 400 }
      )
    }

    // First, insert all customers
    const customerInserts = customersToProcess.map((customer: any) => ({
      user_id: user.id,
      name: customer.name,
      phone: customer.normalizedPhone,
      email: null,
      created_at: new Date().toISOString()
    }))

    const { data: insertedCustomers, error: customerError } = await (supabase as any)
      .from('customers')
      .insert(customerInserts)
      .select('id, name, phone')

    if (customerError || !insertedCustomers) {
      console.error('Error inserting customers:', customerError)
      return NextResponse.json(
        { error: 'Failed to save customers' },
        { status: 500 }
      )
    }

    // Create review requests with staggered scheduling
    const batchSize = 20
    const batchDelayMinutes = 15
    const currentTime = new Date()

    const reviewRequestInserts = insertedCustomers.map((customer: any, index: number) => {
      // Calculate batch number and delay
      const batchNumber = Math.floor(index / batchSize)
      const scheduledFor = new Date(currentTime.getTime() + (batchNumber * batchDelayMinutes * 60 * 1000))

      return {
        id: crypto.randomUUID(),
        user_id: user.id,
        customer_id: customer.id,
        token: generateToken(),
        status: 'scheduled' as const,
        scheduled_for: scheduledFor.toISOString(),
        created_at: new Date().toISOString(),
        nudge_sent: false
      }
    })

    const { data: insertedRequests, error: requestError } = await (supabase as any)
      .from('review_requests')
      .insert(reviewRequestInserts)
      .select('id, scheduled_for, token')

    if (requestError || !insertedRequests) {
      console.error('Error inserting review requests:', requestError)
      return NextResponse.json(
        { error: 'Failed to create review requests' },
        { status: 500 }
      )
    }

    // Calculate summary stats
    const batches = Math.ceil(customersToProcess.length / batchSize)
    const estimatedCompletionMinutes = (batches - 1) * batchDelayMinutes + 5 // +5 for processing time
    const estimatedCompletionTime = new Date(currentTime.getTime() + (estimatedCompletionMinutes * 60 * 1000))

    return NextResponse.json({
      success: true,
      processed: customersToProcess.length,
      pendingSaved: pendingSavedCount,
      batches,
      batchSize,
      batchDelayMinutes,
      estimatedCompletionTime: estimatedCompletionTime.toISOString(),
      estimatedCompletionMinutes,
      requests: insertedRequests.map((req: any) => ({
        id: req.id,
        scheduledFor: req.scheduled_for,
        token: req.token
      }))
    })

  } catch (error) {
    console.error('Bulk upload error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}